# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c20c7526f56e5b1e479a36634f7b4aaa70b8404a5c34915da1fbb6fc127b3b0741825c2a069376eea9f60f9a1e99ca97fa4a93487ed6d999fa3b2e0182ee3f9

test:
  secret_key_base: bce4547fe746dbdafa6d1ed4e5880a195da0c55cefa102f0b1bc6919d9e5a1a33b326c0cf9d5c798cc52e83423930318ac53c129d67472d0d7c2ec896483519c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
